### ISSUE TITLE
example usage

### ISSUE THREAD

**Issue by HannesGitH** [esp-rs/esp-idf-part#8]
how would one use this?

i currently need to increase the app partition size as the default 1MB is to small, how would i do this, using this library?

without using this library i would create the .csv by hand and apply it via `cargo pio espidf menuconfig`

**Comment by jessebraham** [comment]
I don't believe this is the right place to ask, `cargo-pio` does not appear to use this crate at all.

This crate was created for use in [espflash](https://github.com/esp-rs/espflash) and the primary purpose is to parse CSV/binary files and convert between them. I would recommend opening an issue in the [embuild](https://github.com/esp-rs/embuild) repository (where `cargo-pio` lives) instead, as you may be able to get some help there.
